### ISSUE TITLE
A contender spotted

### ISSUE THREAD

**Issue by devkral** [solid/solid#162]
Hello,
I work on the same idea for 5 years. Your project is very good.
Are you interested in collaboration? I would really like an exchangeable format and I think RDF is a dead end (too inflexible).
For more resources:
example (format): https://spkcspider.net/cgi-bin/cgihandler.fcgi/spider/content/access/15/sUCFNXDdVx5TZp7U/view/?raw=true
github: https://github.com/devkral/spkcspider
homepage: https://spkcspider.net

**Comment by RubenVerborgh** [comment]
> I think RDF is a dead end (too inflexible).

But what's an alternative?

How can decentralized data stores do their own thing while still interoperating on a data level with apps?

**Comment by bblfish** [comment]
@devkral For a longer and detailed explanation of @RubenVerborgh's point you may wish to read [Epistemology in the Cloud - on Fake News and Digital Sovereignty](https://medium.com/@bblfish/epistemology-in-the-cloud-472fad4c8282).

**Comment by devkral** [comment]
An alternative is ordered JSON. Why? Because you can map nearly everything to JSON.
And the best thing is:you can hash ordered JSON.
RDF has no order. You need to define an order for hashing. And who says that your order matches one other order.
Why do we want to hash? GDPR.
Imagine a web shop, who just save hashes for recording. The hashes can be validated by a third party, who maybe is able to map hashes to the original Data or can verify that the user is valid.
This means, the web shop or web project doesn't use personal data and doesn't leak them on a breach. Also the amount of bureaucracy is reduced.
Sry for the teaser. I was in hurry.

**Comment by devkral** [comment]
Another reason for JSON. RDF defines some classes. But what is if you need another class? Something nobody had expected. Like Blood type.

**Comment by bblfish** [comment]
You can hash RDF independently of serialisations. See [rdf dataset normalisation](https://json-ld.github.io/normalization/spec/)

**Comment by dmitrizagidulin** [comment]
@devkral all valid concerns. For what it's worth, Solid supports JSON in the form of [JSON-LD](https://json-ld.org/). (This also includes the corresponding dataset canonicalization for hashing, etc.)

**Comment by devkral** [comment]
didn't saw json-ld :).
But still: as far as I see is RDF normalization is very complex (by sorting hashes) also you cannot define some new classes (it is too inflexible). Using this as default is maybe limiting you later.

**Comment by kjetilk** [comment]
Huh? RDF is all about defining new classes... There are literally millions of them...

**Comment by kjetilk** [comment]
So, the fundamental problem here is that the world is not very well described in terms of trees. Trees are for small, constrained pieces of information, but the real world is generally much better described by a graph. If you are constrained to a tree, you will always have to chop up the real world that you're actually describing into those little pieces of information. And before long, you will chop it at arbitrary places that only makes sense for a small application environment. If, OTOH, you try to represent that real world with a graph, you'd do much less of that, and your applications are not going to be that constrained. So, that's why you see some resistance against JSON here. JSON is for those small, constrained information pieces that doesn't reflect the real world as well as we can do with RDF. 

So, RDF is harder to work with, because programming languages tend to be really fixed at those trees. That's actually one of our key challenges, but we're ready to take that on.

**Comment by kjetilk** [comment]
Oh, yeah! :-) But we're trying to Innovate here, you know! Besides, we're not the only ones looking into this stuff. So, obviously, we need tooling that returns a little tree where appropriate, but we also need to try to get people into a little different mindset.

**Comment by devkral** [comment]
sry, you are right: RDF is much better for such kind of content.
