### ISSUE TITLE
Invalid username solid.community

### ISSUE THREAD

**Issue by Serj-Aleks** [solid/solid#205]
https://solid.community/api/accounts/new

Invalid username

Username*
Serj-Aleks

**Comment by 45H** [comment]
Hi!
I think no upper cases are allowed in usernames. But you'll need to confirm this. :)

**Comment by Serj-Aleks** [comment]
thank! and there is! registered!

**Comment by kjetilk** [comment]
OK, great! Anyway, we should really just lowercase the username, no reason why that should result in an error for the user, so I'll label it a bug. Thanks for reporting!

**Comment by 45H** [comment]
@kjetilk By the way, the first account I created on solid.community was https://45H.solid.comnunity/card#me and at the time (soon after the inrupt announcement) I had no issue registering with a username containing an uppercase. So something seems to have changed since then. :)

**Comment by kjetilk** [comment]
>  So something seems to have changed since then. :) Also, for some people (like me), being able to use uppercases in their usernames matters. ;)

Yeah, we had no validation on the usernames at all, which was a bad thing... :-) But since it ends up in the hostname, it makes sense to just downcase it, but then, we wouldn't necessarily need to make it lower-case it for all purposes. I suppose [RFC4343](https://tools.ietf.org/html/rfc4343) is an RFC we need to make sure that we don't violate with our hostnames, but other than that, adding some sophistication could be called for.

**Comment by kjetilk** [comment]
I have had a look around the code, and it seems hard to support a mixed-case username while ensuring that hostnames aren't broken. The username is used in a lot of places in the code, and there are also functions like these: https://github.com/solid/node-solid-server/blob/master/lib/models/account-manager.js#L380 where the username is inferred from the hostname. It would take some effort to track down where that is used, which we would have to return to later. Therefore, I think we should simply downcase usernames now.
