### ISSUE TITLE
Make decisions regarding default vocabularies for footprints

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid#222]
### Long term

Since we're using Linked Data, in the long term, whether data pods use `foaf:name`, `vcard:fn`, or `schema:name` shouldn't really matter.

### Current issue
However, in the short term, app developers need clear expectations about what kind of properties to ask for. If one application writes `foaf:name`, another reads `vcard:fn`, and a third writes `schema:name`, not only will we fail at interoperability, we will also have data inconsistencies.

#### Urgency
Having a default choice is important, because while everything is possible, only one thing can be made easy. E.g., in a JSON-LD context, there can only be one `firstName`; the rest will have to be prefixed names or fully qualified URLs. So which one should it be? Since the dev kit is starting to take shape, this discussion is becoming urgent.

#### Domain-specific
This decision might need to be made per domain, i.e., different for people, photos, etc.
Maybe a good first question is how to model profiles. I see three broad choices:
- FOAF
- vCard
- Schema.org

### Call for input
Good arguments can be made for each one, and please make yours below (I will). But the more important one is that we make a decision and document it.

----
### Example
In [LDflex for Solid](https://github.com/solid/query-ldflex), we currently support;
- `solid.data.user.foaf_name`
- `solid.data.user['foaf:name']`
- `solid.data.user['http://xmlns.com/foaf/0.1/name']`
- `solid.data.user.vcard_fn`
- `solid.data.user['vcard:fn']`
- `solid.data.user['http://www.w3.org/2006/vcard/ns#fn']`
- `solid.data.user.schema_name`
- `solid.data.user['schema:name']`
- `solid.data.user['http://www.schema.org/name']`

However, there can only be one `name`:
- `solid.data.user.name`

and this currently is `http://xmlns.com/foaf/0.1/name`.
But what should it really be?

**Comment by RubenVerborgh** [comment]
I think we should go for Schema.org, to tap into their ecosystem.

I dislike the loose typing and semantics of the ontology, but adoption is crucial.

**Comment by csarven** [comment]
* schema.org: I agree with your view of and reasons for schema.org. Among other things, schema.org overlaps with (or borrows from) DC Terms, and that goes a long way to describe resources without having to require domain-specific vocabularies. That's a useful by-product in context of the choice for a profile model.

* vCard: I don't have stats for this but I think vCard (as a vocabulary, not necessarily vcard-rdf) is clear ahead of everything else in terms of use in diverse systems.

* FOAF: Still relevant and useful alongside existing data and systems but I think it gets increasingly difficult to argue for it given schema.org and vCard as "richer" options with active communities at this time.

[TODO: Migrate this to another issue]
While this issue is primarily from the publisher's perspective, equally important is to write 'best practices' or 'examples in the wild' for consuming applications so that developers don't mold their stuff to one vocabulary, and should aim to be flexible with what they encounter. IMO, the Solid project should always communicate that to keep a flexible application ecosystem as the space expands. So, the long term strategy there is to encourage building robust applications so that when (!) one day Solid(-like) systems change to using the next trendy vocab, we don't suddenly break an ocean of applications.

FWIW, [dokieli](https://github.com/linkeddata/dokieli) will consume whatever it comes across to be (relatively) equivalent, but generates schema.org (for profiles and general-purpose resource descriptions)

**Comment by RubenVerborgh** [comment]
Yes, Postel's law definitely applies, see the very first sentence of this
issue. That's how I see the future too.

**Comment by dmitrizagidulin** [comment]
+1 to using `schema:name`

**Comment by kjetilk** [comment]
I suppose the FOAF co-author would encourage us to use schema.org too... :-)

**Comment by Mitzi-Laszlo** [comment]
You can find more conversation on this subject here https://forum.solidproject.org/t/make-decisions-regarding-default-vocabularies-for-footprints/412

**Comment by melvincarvalho** [comment]
> However, there can only be one name:

@RubenVerborgh just a thought regarding ldflex (which I like alot!)

Could the short form be an array, ordered by preference?  So, you start with foaf, then try vcard, then schema etc.  I think there are other large rdf providers that use name, such as facebook.  It would be odd for people to have different literal values in multiple predicates.  But the approach would get any name that was used.

**Comment by RubenVerborgh** [comment]
> Could the short form be an array, ordered by preference?

Yes and no.

No, in that the path expression is translated into a SPARQL query, and translating such property choices would lead to inefficient queries.

Yes, in that ultimately, reasoning will help us bridge such ontological gaps. So we could ask for `foaf:name`, but the query engine can perform reasoning to deduce that `schema:name` fulfills the same function. I use the same approach for my own data: https://ruben.verborgh.org/articles/queryable-research-data/#reason

So in the short term, agreement will be important.

**Comment by RubenVerborgh** [comment]
> Could the short form be an array, ordered by preference?

Another (actually more pressing) obstacle is that LDflex uses JSON-LD contexts to resolve properties into URLs, and they do not (and cannot) have this concept of preference. LDflex is basically JSON-LD for the Web instead of for documents.

So another way to see this problem is that we need to decide which are going to be the short JSON-LD properties and which will be the long ones.

**Comment by megoth** [comment]
@melvincarvalho @RubenVerborgh could you maybe continue the discussion (if it does continue) on https://forum.solidproject.org/t/make-decisions-regarding-default-vocabularies-for-footprints/412 ?

I understand it's more convenient to continue it here, but in terms of including the broader community (i.e. people not so tech-oriented that they use GitHub a lot) I think Discourse is a better, well, forum for this kind of discussions =P

**Comment by RubenVerborgh** [comment]
In that regard, having the technical part of the discussion here might be a
good idea?

**Comment by megoth** [comment]
> In that regard, having the technical part of the discussion here might be a good idea?

Hmm, that is true. It is a case to case decision, I guess, and you'll figure out what works best for you in those different cases.

I just wanted to reiterate the importance of moving discussions to Discourse in general, to include the broader community ^_^ (It's easy to forget sometimes, after all)
