### ISSUE TITLE
Extended Profile - additional predicates

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid#87]
https://github.com/solid/solid-spec/blob/master/solid-webid-profiles.md#extended-profile
> Solid apps that interact with the WebID profile MUST also load and parse all of the related RDF resources that are linked to from the main profile using the following predicates:
*    http://www.w3.org/2002/07/owl#sameAs
*    http://www.w3.org/2000/01/rdf-schema#seeAlso
*    http://www.w3.org/ns/pim/space#preferencesFile

In cases where person prefers to keep additional profile information in one or more storage. Can main `foaf:PersonalProfileDocument` document, one which someone gets as response after dereferencing WebID, link to additional profiles using for one/any/all of
* [http://xmlns.com/foaf/0.1/primaryTopic](http://xmlns.com/foaf/spec/#term_primaryTopic) (used as reverse)
* [http://www.iana.org/assignments/relation/describedby](http://www.iana.org/assignments/link-relations/link-relations.xhtml)
* [http://www.w3.org/ns/activitystreams#describes](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-describes) (used as reverse)

**Comment by dmitrizagidulin** [comment]
Hi @elf-pavlik! :)
Is your question a more general one, or specifically you'd like to add those 3 predicates to the spec and require those also to be loaded as an extended profile?

**Comment by elf-pavlik** [comment]
I thought about making PR but I thought about discussing it first since IMO just one of them would do. Since LDP alraedy uses `ianarel:describedby` maybe only this one would serve the purpose. On the other hand Solid already recommends linking WebID and `foaf:PersonalProfileDocument` using `foaf:primaryTopic` so this one also comes as reasonable choice, especially that I want to link multiple `foaf:PersonalProfileDocument` resources with a single WebID.

**Comment by dmitrizagidulin** [comment]
@elf-pavlik Let me see if I understand the proposals in this issue. 

1. Proposal to require (or at least optionally support?) that [Extended Profile documents](https://github.com/solid/solid-spec/blob/master/solid-webid-profiles.md#extended-profile) link back to the main WebID Profile doc using `foaf:primaryTopic`.
2. Proposal to require (or optionally support?) that the WebID section of the profile (the `#me` / `foaf:Person` section) links back to the main profile document (the `foaf:PersonalProfileDocument` section) using `ianarel:describedby`. (Which would make it so that the sections would be linked to each other, versus the current situation of 'profile doc links to the person, but not the other way around'.) 
3. Proposal to require (or optionally support?) that Extended Profile documents link back to the main WebID Profile using `as2:describes`. (similar to proposal 1?). (And is this just for the extended profile docs, or is the idea to also have the main profile doc use `as2:describes` to link to the webid/person?)

Is that an accurate summary?

If yes, some questions: 
- Aside from 'symmetrical/two-way linking is nice', what's the use case for having the reverse links?
- What's the use case / advantage of also using `as2:describes`?

**Comment by elf-pavlik** [comment]
```http
GET /0bf5e060-1bca-4067-9fd1-720d56ad965b
Host: idp.example
```

```ttl
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
<#identity> a foaf:Person .
<> a foaf:PersonalProfileDocument ;
  foaf:primaryTopic <#identity> .
<https://super-storage.example/ce152883-c55a-41d5-8252-85bf2062e6e6> a foaf:PersonalProfileDocument ;
  foaf:primaryTopic <#identity> .
<https://hiper-storage.example/30c274f9-fa87-4863-9a6d-399fe994e0e4> a foaf:PersonalProfileDocument ;
  foaf:primaryTopic <#identity> .
```

```http
GET /ce152883-c55a-41d5-8252-85bf2062e6e6
Host: super-storage.example
```
```ttl
<> a foaf:PersonalProfileDocument ;
  foaf:primaryTopic <https://idp.example/0bf5e060-1bca-4067-9fd1-720d56ad965b#identity> .
<https://idp.example/0bf5e060-1bca-4067-9fd1-720d56ad965b#identity> foaf:name "elf Pavlik" .
```

```http
GET /30c274f9-fa87-4863-9a6d-399fe994e0e4
Host: hiper-storage.example
```
```ttl
<> a foaf:PersonalProfileDocument ;
  foaf:primaryTopic <https://idp.example/0bf5e060-1bca-4067-9fd1-720d56ad965b#identity> .
<https://idp.example/0bf5e060-1bca-4067-9fd1-720d56ad965b#identity> foaf:depiction <https://media.example/1c9fe088-bdc1-437c-8cf8-f4f342ceff07> .
```

1. one has single Identity (WebID) - `https://idp.example/0bf5e060-1bca-4067-9fd1-720d56ad965b#identity`
2. one has three profile documents
 * base URI of WebID which only links to other profile documents - `https://idp.example/0bf5e060-1bca-4067-9fd1-720d56ad965b`
 * profile document in first storage with a name - `https://super-storage.example/ce152883-c55a-41d5-8252-85bf2062e6e6`
 * profile document in second storage with an avatar - `https://hiper-storage.example/30c274f9-fa87-4863-9a6d-399fe994e0e4`

This way one can use multiple profile documents to describe a single identity. Clients just need to follow `foaf:primaryTopic` in reverse direction discovered in profile document with URI same as base URI of WebID.

**Comment by dmitrizagidulin** [comment]
I see, thank you for clarifying. At the moment, the spec achieves a similar effect by linking to the other profiles using `sameAs` and `seeAlso` predicates. What would be the benefit of using this other method of linking? Seems more complex to me...

**Comment by elf-pavlik** [comment]
I can most likely use `rdfs:seeAlso` to achieve the same goal, `owl:sameAs` doesn't seem appropriate to me since I want to keep each of those profile documents distinct from another and they all describe same WebID.
